[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm i -g pnpm@11.23.0",
  "pnpm install --no-frozen-lockfile --ignore-scripts"
]

[start]
cmd = "node node_modules/.bin/tsx apps/api/src/index.ts"
